/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nintendo;

import javax.swing.ImageIcon;

/**
 *
 * @author proxc
 */
public class Home11 extends javax.swing.JFrame {

    /**
     * Creates new form Home11
     */
    static ImageIcon icon;
    
    public Home11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_ideas = new javax.swing.JLabel();
        img_upvotes = new javax.swing.JLabel();
        img_awards = new javax.swing.JLabel();
        img_play = new javax.swing.JLabel();
        img_share = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        img_ideas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_ideas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nintendo/icons/idea_25px.png"))); // NOI18N
        img_ideas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_ideasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_ideasMouseExited(evt);
            }
        });

        img_upvotes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_upvotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nintendo/icons/double_up_25px_1.png"))); // NOI18N
        img_upvotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_upvotesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_upvotesMouseExited(evt);
            }
        });

        img_awards.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_awards.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nintendo/icons/trophy_25px_1.png"))); // NOI18N
        img_awards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_awardsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_awardsMouseExited(evt);
            }
        });

        img_play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nintendo/icons/play_25px_1.png"))); // NOI18N
        img_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_playMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_playMouseExited(evt);
            }
        });

        img_share.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_share.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nintendo/icons/share_25px_1.png"))); // NOI18N
        img_share.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                img_shareMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                img_shareMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Awards");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Ideas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Upvoted");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Start Tour");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Share");

        jPanel3.setBackground(new java.awt.Color(23, 129, 191));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("(c) 2017 Nintendo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img_awards, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(91, 91, 91))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(img_ideas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(img_upvotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(img_play, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel5))
                            .addComponent(img_share, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img_awards, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(img_ideas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img_upvotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img_play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img_share, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        bg1.setIcon(new javax.swing.ImageIcon("D:\\Graphics\\Icons\\project11\\Others\\nin.jpg")); // NOI18N
        bg1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bg1MouseDragged(evt);
            }
        });
        bg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg1MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(254, 0, 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(254, 0, 2));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 0, 2));
        jLabel6.setText("Nintendo Switch");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Awards");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(23, 129, 191));
        jLabel8.setText("By KeepToo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bg1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 469, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 470, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(bg1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 201, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 308, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 309, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void img_awardsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_awardsMouseEntered
        // TODO add your handling code here:
        icon = new ImageIcon(getClass().getResource("icons/trophy_25px.png"));
        img_awards.setIcon(icon);
    }//GEN-LAST:event_img_awardsMouseEntered

    private void img_awardsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_awardsMouseExited
        // TODO add your handling code here:
         icon = new ImageIcon(getClass().getResource("icons/trophy_25px_1.png"));
        img_awards.setIcon(icon);
    }//GEN-LAST:event_img_awardsMouseExited

    private void img_ideasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_ideasMouseEntered
        // TODO add your handling code here:
         icon = new ImageIcon(getClass().getResource("icons/idea_25px_1.png"));
        img_ideas.setIcon(icon);
    }//GEN-LAST:event_img_ideasMouseEntered

    private void img_ideasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_ideasMouseExited
        // TODO add your handling code here:
        icon = new ImageIcon(getClass().getResource("icons/idea_25px.png"));
        img_ideas.setIcon(icon);
    }//GEN-LAST:event_img_ideasMouseExited

    private void img_upvotesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_upvotesMouseEntered
        // TODO add your handling code here:
        icon = new ImageIcon(getClass().getResource("icons/double_up_25px.png"));
        img_upvotes.setIcon(icon);
    }//GEN-LAST:event_img_upvotesMouseEntered

    private void img_upvotesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_upvotesMouseExited
        // TODO add your handling code here:
        icon = new ImageIcon(getClass().getResource("icons/double_up_25px_1.png"));
        img_upvotes.setIcon(icon);
    }//GEN-LAST:event_img_upvotesMouseExited

    private void img_playMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_playMouseEntered
        // TODO add your handling code here:
        icon = new ImageIcon(getClass().getResource("icons/play_25px.png"));
        img_play.setIcon(icon);
    }//GEN-LAST:event_img_playMouseEntered

    private void img_playMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_playMouseExited
        // TODO add your handling code here:
        icon = new ImageIcon(getClass().getResource("icons/play_25px_1.png"));
        img_play.setIcon(icon);
    }//GEN-LAST:event_img_playMouseExited

    private void img_shareMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_shareMouseEntered
        // TODO add your handling code here:
        icon = new ImageIcon(getClass().getResource("icons/share_25px.png"));
        img_share.setIcon(icon);
    }//GEN-LAST:event_img_shareMouseEntered

    private void img_shareMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_shareMouseExited
        // TODO add your handling code here:
        icon = new ImageIcon(getClass().getResource("icons/share_25px_1.png"));
        img_share.setIcon(icon);
    }//GEN-LAST:event_img_shareMouseExited
    int xy;
    int xx;
    private void bg1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg1MouseDragged
        // Drag your control
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_bg1MouseDragged

    private void bg1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bg1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel img_awards;
    private javax.swing.JLabel img_ideas;
    private javax.swing.JLabel img_play;
    private javax.swing.JLabel img_share;
    private javax.swing.JLabel img_upvotes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
